services:
  tomcat:
    image: tomcat:9.0.98-jdk17-corretto
    env_file: ".env"
    ports:
      - "${TOMCAT_PORT}:8080"
      - "${TOMCAT_DEBUG_PORT}:8000"
    networks:
      - etendo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${VOLUMES_PATH}/tomcat/webapps:/usr/local/tomcat/webapps
      - ${ATTACH_PATH}:${ATTACH_PATH}
      - ${SOURCE_PATH}:${SOURCE_PATH}
    environment:
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
      - CATALINA_OPTS=${TOMCAT_CATALINA_OPTS}
    command: ["catalina.sh", "jpda", "run"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TOMCAT_PORT}/"]
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 45s
